language:
- node_js
node_js:
- '6'
env:
  global:
  - NODE_ENV=test
services:
  - postgresql
before_script:
  - psql -c 'create database supernova_test;' -U postgres
  - psql -f ./src/server/db/tableCreation.sql -d supernova_test
addons:
  postgresql: 9.6
