branch-defaults:
  deployment-attempt:
    environment: super-nova-server-dev
    group_suffix: null
global:
  application_name: super-nova-server-dev
  branch: null
  default_ec2_keyname: super-nova-server-ssh
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: git
